[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[project]
name = "example"
version = "0.1.0"
description = ""
authors = [
    { name = "Pierce Freeman", email = "pierce@freeman.vc" }
]
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "mountaineer",
]

[project.scripts]
runserver = "example.cli:runserver"
watch = "example.cli:watch"
build = "example.cli:build"

[tool.uv.sources]
mountaineer = { path = "../", editable = true }
